name: dart_smb2
description: SMB2/2.1/3.0 client library with true message multiplexing.
version: 0.1.0

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.0
  pointycastle: ^3.7.0
  asn1lib: ^1.5.0

dev_dependencies:
  test: ^1.24.0
